"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CardGridSkeleton = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const material_1 = require("@mui/material");
const CardGridSkeleton = () => {
    return ((0, jsx_runtime_1.jsx)(material_1.Box, { children: (0, jsx_runtime_1.jsxs)(material_1.Grid, Object.assign({ container: true }, { children: [(0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0), (0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0), (0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0), (0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0), (0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0), (0, jsx_runtime_1.jsx)(material_1.Grid, Object.assign({ item: true, lg: 4, md: 6, sm: 12, xs: 12 }, { children: (0, jsx_runtime_1.jsx)(material_1.Card, Object.assign({ sx: { margin: 2 } }, { children: (0, jsx_runtime_1.jsx)(material_1.Skeleton, { variant: "rectangular", width: "100%", height: 100 }, void 0) }), void 0) }), void 0)] }), void 0) }, void 0));
};
exports.CardGridSkeleton = CardGridSkeleton;
