"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserProfile = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const material_1 = require("@mui/material");
require("./userProfile.scss");
const UserProfile = ({ user, viewerIsUser }) => {
    const additionalDetailsSection = viewerIsUser ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(material_1.Divider, { sx: { margin: 1 } }, void 0), (0, jsx_runtime_1.jsx)(material_1.Typography, Object.assign({ variant: "h5", className: "user--text-details" }, { children: "Additional Details" }), void 0), (0, jsx_runtime_1.jsx)(material_1.Typography, Object.assign({ variant: 'body1', className: "user--text-details" }, { children: "Ready to bring engaging lesson plans to the classroom? Sign up now!" }), void 0), (0, jsx_runtime_1.jsx)(material_1.Button, Object.assign({ className: 'stripe--button', variant: "contained" }, { children: "Connect with Stripe!" }), void 0), (0, jsx_runtime_1.jsxs)(material_1.Typography, Object.assign({ variant: 'body1', className: "user--text-details" }, { children: ["We use ", (0, jsx_runtime_1.jsx)("a", Object.assign({ href: "https://stripe.com/en-US/connect", target: "_blank", rel: "noopener noreferrer" }, { children: " Stripe" }), void 0), " to make payments seamless and secure."] }), void 0)] }, void 0)) : null;
    return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsxs)(material_1.Box, Object.assign({ className: "user--text" }, { children: [(0, jsx_runtime_1.jsx)("h1", { children: "User Profile" }, void 0), (0, jsx_runtime_1.jsxs)(material_1.Card, Object.assign({ sx: { width: 350, boxShadow: 1, padding: 5 } }, { children: [(0, jsx_runtime_1.jsx)(material_1.Avatar, { src: user.avatar, sx: { width: 56, height: 56, marginLeft: "40%" } }, void 0), (0, jsx_runtime_1.jsx)(material_1.Divider, { sx: { margin: 1 } }, void 0), (0, jsx_runtime_1.jsx)(material_1.Typography, Object.assign({ variant: "h5", className: "user--text-details" }, { children: "Details" }), void 0), (0, jsx_runtime_1.jsxs)(material_1.Typography, Object.assign({ className: "user--text-details" }, { children: ["Name: ", user.name] }), void 0), (0, jsx_runtime_1.jsxs)(material_1.Typography, Object.assign({ className: "user--text-details" }, { children: ["Email: ", user.contact] }), void 0), additionalDetailsSection] }), void 0)] }), void 0) }, void 0));
};
exports.UserProfile = UserProfile;
